# Generated by Django 4.2.11 on 2024-03-15 13:54

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to=app.models.file_path)),
                ('share', models.UUIDField(null=True, unique=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True, verbose_name='Размер файла')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Комментарий к файлу')),
                ('url', models.URLField(max_length=1024, null=True, verbose_name='Ссылка на файл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
